service: wodify-client-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  timeout: 15

functions:
  getWorkout:
    handler: src/handler.getWorkoutHandler
    events:
      - httpApi:
          path: /workout
          method: post
  signinCrossfit:
    handler: src/handler.signinCrossfitHandler
    events:
      - httpApi:
          path: /signin-crossfit
          method: post

plugins:
  - serverless-plugin-typescript
