service: wodify-client-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  timeout: 15

package:
  individually: true

functions:
  getWorkout:
    handler: src/handler.getWorkoutHandler
    events:
      - httpApi:
          path: /workout
          method: post
  signin:
    handler: src/handler.signinHandler
    events:
      - httpApi:
          path: /signin
          method: post
      - httpApi: # deprecated (but still supported)
          path: /signin-crossfit
          method: post

plugins:
  - serverless-plugin-typescript
